### ISSUE TITLE
Add notification system

### ISSUE THREAD

**Issue by jboyer87** [arc2nd/CSC480_project#76]
We need to create a script or something that sends out notifications. Our SRS says that this should be daily. I think it just needs to:
- Query the DB for chores that are due today
- Get the assigned users
- Send each assigned user an email with the chores that they have to complete that day
The script can be standalone. We can explain that it is supposed to run as a cronjob (linux) or scheduled task (windows) depending on the platform.

**Comment by jboyer87** [comment]
@arc2nd Do you feel comfortable doing this one?

**Comment by arc2nd** [comment]
yeah, I think I can tackle that tonight
