### ISSUE TITLE
Send emails when a reward is claimed

### ISSUE THREAD

**Issue by jboyer87** [arc2nd/CSC480_project#94]
@arc2nd Think you can handle this one? I think you're more familiar with how the email system works.

**Comment by arc2nd** [comment]
Yeah, I'll get started on this today

**Comment by arc2nd** [comment]
I got this working. I'm trying to figure out a way to incorporate it into the app. 

I decided to use the gmail smtp server to send messages. I don't want to use my own personal email account though. So I was going to make a ChoreExplore account. However I need to store a password to use it. As I still haven't figured out a good cross-platform crypto we can all use I don't want to store that password in plaintext. 

So still working on that aspect.

**Comment by jboyer87** [comment]
I think the test server should be fine, same as for the notifications. If you get that much working, we could demo it if we wanted, and just leave configuration details in there for the "user". Since we aren't actually selling this or using it in a production environment, we might not even need that.
